export const GET_RANDOM_JOKES = 'GET_RANDOM_JOKES';
export const GET_JOKES_SUCCESS = 'GET_JOKES_SUCCESS';

export const FAVORITE_JOKE = 'FAVORITE_JOKE';
export const UNFAVORITE_JOKE = 'UNFAVORITE_JOKE';

export const TOGGLE_AUTO_ADD_JOKES = 'TOGGLE_AUTO_ADD_JOKES';

export const START_AJAX_CALL = 'START_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';
